version: 2
updates:
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: weekly
      time: "10:00"
    open-pull-requests-limit: 10
    reviewers:
      - asmahood
    ignore:
      - dependency-name: css-loader
        versions:
          - "> 4.3.0"
      - dependency-name: eslint-plugin-testing-library
        versions:
          - "> 3.10.1"
      - dependency-name: html-webpack-plugin
        versions:
          - "> 4.5.0"
      - dependency-name: "@pmmmwh/react-refresh-webpack-plugin"
        versions:
          - "> 0.4.2"
      - dependency-name: postcss-flexbugs-fixes
        versions:
          - "> 4.2.1"
      - dependency-name: style-loader
        versions:
          - "> 1.3.0"
      - dependency-name: "@svgr/webpack"
        versions:
          - "> 5.4.0"
      - dependency-name: web-vitals
        versions:
          - "> 0.2.4"
      - dependency-name: eslint-config-prettier
        versions:
          - 8.2.0
