version: 2
updates:
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: daily
    reviewers:
      - asmahood
    labels:
      - "type::Dependencies"
      - "dep::Javascript"
  - package-ecosystem: docker
    directory: "/"
    schedule:
      interval: daily
    reviewers:
      - asmahood
    labels:
      - "type::Dependencies"
      - "dep::Docker"
