name: Publish Docker image
on:
  release:
    types: [created]
jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build the tagged Docker image
        run: docker build --rm --no-cache -t uwpokerclub/app:${GITHUB_REF##*/} -t uwpokerclub/app:latest .
      - name: Push the tagged Docker image
        run: docker push uwpokerclub/app:${GITHUB_REF##*/}
      - name: Push the latest Docker image
        run: docker push uwpokerclub/app:latest
  update_gke_cluster:
    name: Update the kubernetes cluster in GKE
    needs: push_to_registry
    runs-on: ubuntu-latest
    steps:
      - name: Deploy Stage
        id: deploy
        run: |
          tag=${GITHUB_REF##*/}
          curl -X POST \
            -H "Accept: application/vnd.github.v3+json" \
            -H "Authorization: token ${{ secrets.DEPLOY_USER_TOKEN }}" \
            -d "{\"client_payload\": {\"api\": \"$tag\"}, \"event_type\": \"update\"}" \
            https://api.github.com/repos/uwpokerclub/charts/dispatches